version: '3'

services:
  db:
    container_name: db_postgres
    image: postgres:14.3-alpine
    restart: always
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
